"""
Phase 1 — ArabicDiacritizer  [NOT CALLED FROM THE PIPELINE]

This module is no longer part of the active pipeline.  Diacritization of
chunk/page text was removed because downstream NLP tools and the LLM
summariser work better on unvowelised text.  Only the final video script
(generated by BookSummarizer._diacritize) receives harakat, using Mishkal
directly.  This file is kept as a standalone utility should it be needed.

Primary  : farasapy — local Python wrapper for the Farasa toolkit.
           Runs fully offline after a one-time ~241 MB model download.
           Install: pip install farasapy
Fallback : Mishkal — fully offline, slightly lower accuracy.
           Install: pip install mishkal
"""

from __future__ import annotations

import logging
import re
import warnings

logger = logging.getLogger(__name__)

# Silence noisy third-party warnings emitted during model loading
logging.getLogger("farasa").setLevel(logging.ERROR)


class ArabicDiacritizer:
    """
    Adds Harakat to Arabic text.

    Args:
        chunk_size: Max characters per diacritization call.
    """

    def __init__(self, chunk_size: int = 1500):
        self.chunk_size = chunk_size
        self._farasa: object | None = None   # lazy-initialised

    # ------------------------------------------------------------------ #
    #  Public API                                                          #
    # ------------------------------------------------------------------ #

    def diacritize(self, text: str) -> str:
        """Return diacritized version of `text`."""
        if not text.strip():
            return text
        try:
            return self._diacritize_farasa(text)
        except Exception as exc:  # noqa: BLE001
            logger.warning("Farasa diacritization failed (%s) — falling back to Mishkal.", exc)
            return self._diacritize_mishkal(text)

    def diacritize_pages(self, pages) -> list:
        """In-place diacritization of a list of RawPage objects."""
        for page in pages:
            if page.raw_text.strip():
                page.raw_text = self.diacritize(page.raw_text)
                logger.debug("Page %d diacritized.", page.page_number)
        return pages

    # ------------------------------------------------------------------ #
    #  farasapy backend (primary)                                          #
    # ------------------------------------------------------------------ #

    def _get_farasa(self):
        """Lazy-initialise the FarasaDiacritizer (downloads model once)."""
        if self._farasa is None:
            try:
                import urllib3  # noqa: PLC0415
                urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
            except Exception:  # noqa: BLE001
                pass
            from farasa.diacratizer import FarasaDiacritizer  # noqa: PLC0415
            self._farasa = FarasaDiacritizer()
            logger.info("Farasa diacritizer initialised.")
        return self._farasa

    def _diacritize_farasa(self, text: str) -> str:
        diacritizer = self._get_farasa()
        chunks  = self._split_chunks(text)
        results = []
        for chunk in chunks:
            result = diacritizer.diacritize(chunk)
            # farasapy returns a list when given a string; join if needed
            if isinstance(result, list):
                result = " ".join(result)
            results.append(result)
        return " ".join(results)

    # ------------------------------------------------------------------ #
    #  Mishkal fallback                                                    #
    # ------------------------------------------------------------------ #

    def _diacritize_mishkal(self, text: str) -> str:
        try:
            from mishkal.tashkeel import TashkeelClass  # noqa: PLC0415
        except ImportError as exc:
            raise ImportError(
                "Neither farasapy nor Mishkal is available.\n"
                "  farasapy : pip install farasapy\n"
                "  Mishkal  : pip install mishkal"
            ) from exc

        tashkeel = TashkeelClass()
        chunks   = self._split_chunks(text)
        results  = [tashkeel.tashkeel(chunk) for chunk in chunks]
        return " ".join(results)

    # ------------------------------------------------------------------ #
    #  Helpers                                                             #
    # ------------------------------------------------------------------ #

    def _split_chunks(self, text: str) -> list[str]:
        """Split on sentence boundaries, respecting chunk_size."""
        sentences = re.split(r'(?<=[.؟!])\s+', text)
        chunks, current = [], ""
        for sent in sentences:
            if len(current) + len(sent) > self.chunk_size:
                if current:
                    chunks.append(current.strip())
                current = sent
            else:
                current += " " + sent
        if current.strip():
            chunks.append(current.strip())
        return chunks or [text]


# Back-compat alias used in pipeline.py
FarasaDiacritizer = ArabicDiacritizer
